apiVersion: 1

# Mark provisioned data sources for deletion if they're removed from this file
prune: false

datasources:
  - name: Gauge Database
    type: postgres
    access: proxy
    orgId: 1
    uid: psql-gauge
    isDefault: true
    url: $DATABASE_HOST:$DATABASE_PORT
    database: $DATABASE_NAME
    user: $DATABASE_USER
    secureJsonData:
      password: $DATABASE_PASSWORD
    jsonData:
      sslmode: disable
      connMaxLifetime: 14400
      maxOpenConns: 100
